In [18]:
import tensorflow as tf

In [19]:
x = [[1.]]

m = tf.matmul(x, x)
m

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [20]:
x = tf.constant([[1, 9],[3, 6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [21]:
x = tf.add(x, 1)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]], dtype=int32)>